name: Deploy Application Gateway

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: 'environment to deploy'
        default: dev
  push:
    branches:
      - main
    paths:
      - 'envs/dev/application-gateway/**'
      - 'modules/application-gateway/**'

jobs:
  deploy:
    uses: ./.github/workflows/reusable-terraform-module-deploy.yml
    with:
      environment: ${{inputs.environment}}
      working_directory: envs/dev/application-gateway
      backend_key: appgw-dev.tfstate
    secrets: inherit