
    name: Terraform resuable module deployment

    on:
      workflow_call:
        inputs:
          environment:
            description: 'Environment to deploy to'
            required: true
            default: 'dev'
            type: string
          working_directory:
            description: 'Module directory'
            type: string
            required: true
          backend_key:
            description: "Backend key for maintainer state"
            type: string
            required: true
          

    permissions:
      id-token: write   # ✅ REQUIRED for Azure OIDC
      contents: read

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_USE_OIDC: true


    jobs:
      deploy-bootstrap:
        uses: ./.github/workflows/terraform-bootstrap-deploy.yml
        with:
          environment: ${{ inputs.environment }}
        secrets: inherit

      deploy-module-infra:
        runs-on: ubuntu-latest
        needs:
          - deploy-bootstrap

        steps:
          # Checkout Terraform Repo
          - name: Checkout Terraform Repo
            uses: actions/checkout@v4
            with:
              ref: main
              token: ${{ secrets.TF_REPO_TOKEN }}

          - name: List terraform repo Files
            run: ls -ltr

          # Setup Terraform
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3

          # Azure Login
          - name: Azure Login
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.ARM_CLIENT_ID }}
              tenant-id: ${{ secrets.ARM_TENANT_ID }}
              subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          
            # Terraform Init
          - name: Terraform Init
            working-directory: ${{inputs.working_directory}}
            run: terraform init -backend-config="resource_group_name=rg-bootstrap-${{ inputs.environment }}" -backend-config="storage_account_name=storageacttfstate${{ inputs.environment }}" -backend-config="container_name=tf-state-${{ inputs.environment }}" -backend-config="${{inputs.backend_key}}"
          
          # Terraform Validate
          - name: Terraform Validate
            working-directory: ${{inputs.working_directory}}
            run: terraform validate

          - name: List Terraform Files
            run: ls -R ${{inputs.working_directory}}

          # Terraform Plan
          - name: Terraform Plan
            working-directory: ${{inputs.working_directory}}
            run: terraform plan -out=tfplan

          # Terraform Apply
          - name: Terraform Apply
            if: github.ref == 'refs/heads/main'
            working-directory: ${{inputs.working_directory}}
            run: terraform apply -auto-approve tfplan


      # 🔐 DESTROY (with approval)
      destroy-module-infra:
        needs: [deploy-module-infra]
        runs-on: ubuntu-latest
        # 👇 THIS IS THE MAGIC
        environment: ${{ inputs.environment }}

        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              ref: main
              token: ${{ secrets.TF_REPO_TOKEN }}

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3

          - name: Azure Login
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.ARM_CLIENT_ID }}
              tenant-id: ${{ secrets.ARM_TENANT_ID }}
              subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

          - name: Reconnect to Backend to get the state
            working-directory: ${{inputs.working_directory}}
            run: terraform init -reconfigure -backend-config="resource_group_name=rg-bootstrap-${{ inputs.environment }}" -backend-config="storage_account_name=storageacttfstate${{ inputs.environment }}" -backend-config="container_name=tf-state-${{ inputs.environment }}" -backend-config="${{inputs.backend_key}}"

          - name: Module infra destroy
            working-directory: ${{inputs.working_directory}}
            run: |
              terraform destroy -auto-approve 

      destroy-bootstrap:
        needs: [destroy-module-infra]
        uses: ./.github/workflows/terraform-bootstrap-destroy.yml
        secrets: inherit
